=== ZFIN/zfin/home/WEB-INF/conf/properties.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:jxb="http://java.sun.com/xml/ns/jaxb">

    <xs:element name="ApplicationProperties">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Web" />
                <xs:element ref="Wiki" />
                <xs:element ref="Path" />
                <xs:element ref="GBrowse" />
                <xs:element ref="Blast" />
                <xs:element ref="Email" />
                <xs:element ref="Logging" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Web">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="backgroundColor" type="xs:string"/>
                <xs:element name="headerColor" type="xs:string"/>
                <xs:element name="highlightColor" type="xs:string"/>
                <xs:element name="highlighterColor" type="xs:string"/>
                <xs:element name="linkbarColor" type="xs:string"/>
                <xs:element name="sidebarColor" type="xs:string"/>
                <xs:element name="domain" type="xs:string"/>
                <!--<xs:element name="quartzEnabled" type="xs:boolean" default="false"/>-->
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Wiki">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="username" type="xs:string"/>
                <xs:element name="password" type="xs:string"/>
                <xs:element name="InterfaceHostname" type="xs:string"/>
                <xs:element name="IndexerHostname" type="xs:string"/>
                <xs:element name="PushToWiki" type="xs:boolean" default="false"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Path">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Server" />
                <xs:element name="cookiePath" type="xs:string"/>
                <xs:element name="Webdriver" type="xs:string"/>
                <xs:element name="FtpRootPath" type="xs:string"/>
                <xs:element name="imageLoadPath" type="xs:string"/>
                <xs:element name="loadUpFull" type="xs:string"/>
                <xs:element name="PdfPath" type="xs:string"/>
                <xs:element name="IndexPath" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GBrowse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gbrowse" type="xs:string"/>
                <xs:element name="gbrowseImg" type="xs:string"/>
                <xs:element name="gbrowseDB" type="xs:string"/>
                <xs:element name="gbrowseDBHost" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Blast">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="WebHost" type="BlastParameters" />
                <xs:element name="BlastServer" type="BlastParameters"/>
                <xs:element name="Target" type="xs:string"/>
                <xs:element name="DistributedQueryPath" type="xs:string"/>
                <xs:element name="KeyPath" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="BlastParameters">
        <xs:sequence>
            <xs:element name="DatabasePath" type="xs:string"/>
            <xs:element name="GetBinary" type="xs:string"/>
            <xs:element name="PutBinary" type="xs:string"/>
            <xs:element name="User" type="xs:string"/>
            <xs:element name="HostName" type="xs:string"/>
            <xs:element name="BinaryPath" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>


    <xs:element name="Email">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="adminEmailAddress" type="xs:string"/>
                <xs:element name="validationEmailOther" type="xs:string"/>
                <xs:element name="requestNewAnatomyTerm" type="xs:string"/>
                <xs:element name="ln54Contact" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Logging">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="logFileName" type="xs:string"/>
                <xs:element name="logFileSize" type="xs:string"/>
                <xs:element name="MaxLogFiles" type="xs:int"/>
                <xs:element name="logPattern" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Server" >
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" />
            <xs:attribute name="port" type="xs:int" />
            <xs:attribute name="securePort" type="xs:int" />
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ZFIN/zfin/test/zfin-properties-test.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<ApplicationProperties xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../home/WEB-INF/conf/properties.xsd">
    <Web>
        <backgroundColor>#2244</backgroundColor>
        <headerColor>#7357</headerColor>
        <highlightColor>#4437</highlightColor>
        <highlighterColor>#7743</highlighterColor>
        <linkbarColor>#9980</linkbarColor>
        <sidebarColor>#2234</sidebarColor>
    </Web>
    <Path>
        <Server name="localhost" port="8080" securePort="8443"></Server>
        <cookiePath>cgi-bin_frost</cookiePath>
        <Webdriver>cgi-bin/webdriver</Webdriver>
        <FtpRootPath>/ftp/zfin</FtpRootPath>
        <imageLoadPath>/image/load</imageLoadPath>
        <loadUpFull>/image/full</loadUpFull>
        <PdfPath>/pdf/</PdfPath>
        <IndexPath>/werter</IndexPath>
    </Path>
    <Email>
        <adminEmailAddress>zfin@zfin.org</adminEmailAddress>
    </Email>
    <Logging>
        <logFileName>zfin_logger.log</logFileName>
        <logFileSize>1</logFileSize>
        <MaxLogFiles>10</MaxLogFiles>
        <logPattern>%d [%t] %-5p %c{2} - %m%n</logPattern>
    </Logging>
</ApplicationProperties>
